// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(Queryable, Debug, Clone, Serialize, Deserialize)]
#[diesel(table_name = post)]
pub struct Post {
    pub id: i32,
    pub name: String,
}

#[derive(Queryable, Debug, Clone, Serialize, Deserialize)]
#[diesel(table_name = users)]
pub struct User {
    pub id: i32,
    pub name: String,
    pub age: i32,
}
